### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ji4ozhu** [NTDLS/AutoUpdate#1]
1>  CXMLCompression.Cpp
1>c1xx : fatal error C1083: 无法打开源文件:“..\@Libraries\CXML\CXMLCompression.Cpp”: No such file or directory
1>  CXMLReader.Cpp
1>c1xx : fatal error C1083: 无法打开源文件:“..\@Libraries\CXML\CXMLReader.Cpp”: No such file or directory
1>  CXMLWriter.Cpp
1>c1xx : fatal error C1083: 无法打开源文件:“..\@Libraries\CXML\CXMLWriter.Cpp”: No such file or directory
1>  CStringBuilder.Cpp
1>c1xx : fatal error C1083: 无法打开源文件:“..\@Libraries\CStringBuilder\CStringBuilder.Cpp”: No such file or directory
1>  CService.Cpp
1>c1xx : fatal error C1083: 无法打开源文件:“..\@Libraries\CService\CService.Cpp”: No such file or directory

**Comment by NTDLS** [comment]
Those missing files should be pulled from their respective GitHub repositories as submodules.
